### ISSUE TITLE
[Feat] Print URL bars correctly with -rec

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [thomaschiozzi-tndigit/jgo#7]
- The current implementation of -rec does print URL bars correctly. 
- The current implementation "standard" does not print URL bars correctly. 
  - For example, it should correctly format and display a URL like \/\/oidc.registry.servizicie.interno.gov.it.

**Comment by thomaschiozzi-tndigit** [comment]
This is fixed by https://github.com/thomaschiozzi-tndigit/jgo/pull/11
