### ISSUE TITLE
[Feat] Avoid Adding _jgo.jwt.head for Root JWTs with -rec

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [thomaschiozzi-tndigit/jgo#8]
- When using the -rec option for root JWTs, it print _jgo.jwt.head also for the ROOT Header fields. 
- This feature request is to make it possible to omit _jgo.jwt.head for root JWTs, simplifying the reading

`"_jgo.jwt.head": {
    "alg": "RS256",
    "kid": "68e99fa9-7013-49dd-852e-b47187fd8da7",
    "typ": "entity-statement+jwt"
}`

**Comment by thomaschiozzi-tndigit** [comment]
This is fixed by https://github.com/thomaschiozzi-tndigit/jgo/pull/11
